#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
@Author: chenzhen
@Date: 2019-08-28 10:25:40
@LastEditTime: 2020-04-22 15:01:56
@LastEditors: chenzhen
@Description:
'''
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import serving_pb2 as serving__pb2


class MatrixSlowServingStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/matrixslow.serving.MatrixSlowServing/Predict',
                request_serializer=serving__pb2.PredictReq.SerializeToString,
                response_deserializer=serving__pb2.PredictResp.FromString,
                )


class MatrixSlowServingServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatrixSlowServingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=serving__pb2.PredictReq.FromString,
                    response_serializer=serving__pb2.PredictResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'matrixslow.serving.MatrixSlowServing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MatrixSlowServing(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/matrixslow.serving.MatrixSlowServing/Predict',
            serving__pb2.PredictReq.SerializeToString,
            serving__pb2.PredictResp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
