# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import serving_pb2 as serving__pb2


class MatrixSlowServingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/matrixslow.serving.MatrixSlowServing/Predict',
        request_serializer=serving__pb2.PredictReq.SerializeToString,
        response_deserializer=serving__pb2.PredictResp.FromString,
        )


class MatrixSlowServingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MatrixSlowServingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=serving__pb2.PredictReq.FromString,
          response_serializer=serving__pb2.PredictResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'matrixslow.serving.MatrixSlowServing', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
